# dev docker compose
services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: metis
    volumes:
      - metis_db:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  metis_db:
